### ISSUE TITLE
How do you update master directory? 

### ISSUE THREAD

**Issue by ceruberu** [K0lb3/KonoSuba--Fantastic-Days-asset-downloader#1]
First, thanks for your great work here.

I see the master json currently lists 150 members until Bumpy Camel Ride Iris.

If I continue to use this downloader, how do I update jsons in master?

**Comment by K0lb3** [comment]
Recap from the discord chat:

- encryption/decryption will stay private for now
- ~~master files will be updated by hand~~

4c6838d8ddb85569fde73edfd6abc917d95ca036 added update_master.py which uses another endpoint to encrypt and decrypt the requests required to request the master files.
